### PR TITLE
Fixes missing code actions for `wrong-import-position`

### LINKED ISSUE #182: Add code action to organize imports when there's a "wrong import position" warning
Ref: https://github.com/microsoft/vscode-pylint/issues/43

There are two things that needs to be done:

- [ ] Create quick fix for warning code `C0413:wrong-import-position` that triggers the `editor.action.organizeImports` action
- [ ] Add unit test 

The code for the first step will be similar to the one here: https://github.com/microsoft/vscode-pylint/blob/2fae19e66aaf079c3dc190b81f913695ac65b078/bundled/tool/server.py#L243

And the unit tests will be similar to this: https://github.com/microsoft/vscode-pylint/blob/2fae19e66aaf079c3dc190b81f913695ac65b078/src/test/python_tests/test_code_actions.py#L23

### PR DESCRIPTION
**Pull request by ketozhang**
* Fixes #182 
* Fix unit test, `test_command_code_action`, input parameter, `command`, needs to be a list since there can be more than one code actions.

### CODE REVIEW

**Comment by ketozhang** [comment]
@microsoft-github-policy-service agree

**Comment by ketozhang** [comment]
@microsoft-github-policy-service agree

**Comment by ketozhang** [comment]
@microsoft-github-policy-service agree

**Comment by karthiknadig** [comment]
Thanks for this PR. But, as you pointed out [here](https://github.com/microsoft/vscode-pylint/issues/182#issuecomment-1289785166), there isn't a quick fix for this that will just work. Closing this for now. We can revisit this.

**Pull request closed without merging**
